- name: Initialiser la VM pour environnement DevOps
  hosts: all
  become: true
  vars:
    # dev_user: jules
    ssh_private_key: ~/.ssh/id_rsa
    node_version: "20"
    admin_user: root

  roles:
    - common
    - docker
    - nodejs
    - chrome
    - aws_cli
    - angular_cli
    - install_terraform
  #- firewall
  # - user
